# This workflow builds the sphinx docs

name: Sphinx Docs Build

on:
  push:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      with:
        persist-credentials: false
    - name: Install hyswap, dependencies, and Sphinx then build docs
      shell: bash -l {0}
      env:
        API_USGS_PAT: ${{ secrets.API_USGS_PAT }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install .
        sudo apt-get update -y
        sudo apt-get upgrade -y
        sudo apt-get install -y xdg-utils
        sudo apt-get install -y lynx
        sudo apt-get install -y graphviz
        sudo apt-get install -y pandoc
        pydeps hyswap -T png --max-bacon=3 --cluster
        mv hyswap.png docs/source/reference/hyswap.png
        export API_USGS_PAT
        (cd docs && make docs)
        (cd docs && make html)
    - name: Debug
      run: |
        echo $REF
        echo $EVENT_NAME
        echo ${{ github.event_name == 'push' }}
        echo ${{ github.ref == 'refs/heads/main' }}
        echo ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@881db5376404c5c8d621010bcbec0310b58d5e29
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVENT_NAME: ${{ github.event_name }}
          REF: ${{ github.ref }}
          BRANCH: gh-pages
          FOLDER: docs/build/html
